# golangci-lint configuration for iam-services
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
    - bin
  skip-files:
    - ".*\\.pb\\.go$"  # Skip protobuf generated files
    - ".*_test\\.go$"  # Skip test files from some linters

linters:
  enable:
#    - revive       # Code quality and style
#    - errcheck     # Check error returns
#    - gosec        # Security issues
    - goconst      # Repeated strings
    - gofmt        # Code formatting
#    - goimports    # Import formatting
    - misspell     # Spelling mistakes
    - ineffassign  # Unused assignments
    - staticcheck  # Static analysis
    - typecheck    # Type errors
    - unused       # Unused code
    - govet        # Go vet analysis
 #   - unconvert    # Unnecessary conversions
  disable:
    - structcheck  # Deprecated
    - deadcode     # Deprecated
    - varcheck     # Deprecated

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: package-comments
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
  
  errcheck:
    check-blank: true
    check-type-assertions: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G115  # We handle integer overflow manually
  
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/tvttt/iam-services

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Exclude known issues in generated code
    - path: \.pb\.go$
      linters:
        - revive
        - stylecheck
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
